// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxTfntCFFFlEMfOZIpZIcCVk4nyUOkYE',
    appId: '1:601423066247:android:bf421de214e0fac0d77422',
    messagingSenderId: '601423066247',
    projectId: 'myfirstproject-355df',
    databaseURL: 'https://myfirstproject-355df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirstproject-355df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgDpJpYGNEDQpSUVJAbwnA6S4EgI09BzA',
    appId: '1:601423066247:ios:10e5e6cdbba18031d77422',
    messagingSenderId: '601423066247',
    projectId: 'myfirstproject-355df',
    databaseURL: 'https://myfirstproject-355df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirstproject-355df.appspot.com',
    androidClientId: '601423066247-fl3st2oe496imm0osiuau2ti7k50gt41.apps.googleusercontent.com',
    iosClientId: '601423066247-oajvpqhnc1lk8snjos2d5t0jut37hk1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryApp',
  );
}
